"""Split Danya's collage into animatable layers and inline them into index.html.

Run:  python build.py   (needs Pillow + numpy)
Reads source/collage.webp; rewrites the @@ASSETS block inside index.html.
Why data URIs inlined in the page: pixels loaded from file:// taint the canvas, so
getImageData (which the warp needs) would throw; and a separate assets file doesn't
survive single-file previews. Data URIs are same-origin, so it works by double-click.
"""
import base64, io, json
from pathlib import Path
import numpy as np
from PIL import Image

HERE = Path(__file__).parent
im = np.asarray(Image.open(HERE / 'source/collage.webp').convert('RGB')).astype(np.float32)
H, W, _ = im.shape

# Geometry measured from the image (see NOTES.md)
CIRCLE = dict(x=391, y=256, r=60)
RECT = dict(x=117, y=414, w=103, h=152)
PANEL = dict(x=59, y=415, w=469, h=187)
AVATAR = dict(x=42, y=562, r=22)   # app UI icon left in by the screenshot, not part of the art

yy, xx = np.mgrid[0:H, 0:W]

def patch(cx, cy, r, dx, dy, feather):
    """Fill a disc with a feathered copy of the texture offset by (dx, dy)."""
    d = np.hypot(xx - cx, yy - cy)
    m = np.clip((r + feather - d) / feather, 0, 1)[..., None]
    src = np.roll(np.roll(im, -dy, 0), -dx, 1)
    return im * (1 - m) + src * m

im = patch(CIRCLE['x'], CIRCLE['y'], CIRCLE['r'] + 4, 0, -128, 10)
im = patch(AVATAR['x'], AVATAR['y'], AVATAR['r'], 0, -60, 6)
# the rectangle sits on the panel's white left end: refill it with the streaky white to its right
r = RECT
im[r['y']:r['y'] + r['h'] + 3, r['x'] - 3:r['x'] + r['w'] + 3] = \
    im[r['y']:r['y'] + r['h'] + 3, r['x'] + 106:r['x'] + r['w'] + 112]

def data_uri(arr, fmt='JPEG', q=92):
    b = io.BytesIO()
    Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8)).save(b, fmt, quality=q)
    return f'data:image/{fmt.lower()};base64,' + base64.b64encode(b.getvalue()).decode()

p = PANEL
assets = {
    'W': W, 'H': H, 'circle': CIRCLE, 'rect': RECT, 'panel': PANEL,
    'bg': data_uri(im),
    'panelImg': data_uri(im[p['y']:p['y'] + p['h'], p['x']:p['x'] + p['w']]),
}
page = HERE / 'index.html'
html = page.read_text(encoding='utf-8')
b, e = '// @@ASSETS-BEGIN (generated by build.py, do not edit)\n', '// @@ASSETS-END'
i, j = html.index(b) + len(b), html.index(e)
html = html[:i] + 'window.ASSETS = ' + json.dumps(assets) + ';\n' + html[j:]
page.write_text(html, encoding='utf-8', newline='\n')
print('assets inlined into index.html,', round(page.stat().st_size / 1024), 'KB')
